version: '3'
services:
 loader:
   build: .
   # Connects a local dir with log files to load
   volumes:
    - ${INPUT_FILES_DIR}:/app_data/input_files

 idfa_db:
   image: redis

 gaid_db:
   image: redis

 adid_db:
   image: redis

 dvid_db:
   image: redis
